Update symlndotfiles
Now uses getopts
New options

diff --git a/symlndotfiles b/symlndotfiles
--- a/symlndotfiles
+++ b/symlndotfiles
@@ -10,51 +10,94 @@ ${0##*/}
 *.swp*
 )
 
-USAGE="Usage: $0 [options]
+USAGE="Usage: $(basename "$0") [options]
 Options:
   -h   Show usage
-  -n   Do not use ln -sf for all matches
+  -l   List all files exluding ignored ones
+  -n   Never use ln -sf, don't even ask
   -f   Use ln -sf for all matches
+  -o   Hide errors
 
 If -n or -f are omitted you will be asked whether or not to use
 force (deleting the file at the destination) for creating a symlink,
 if a file at the destination already exists.
 "
 
-if [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; then
-    printf "$USAGE"
-    exit
-else
-    files=$(find $PWD -type f)
 
-    for file in $files; do
-        dir=${file%/*}
-        dir=${dir#*$PWD}
-        dir=${dir#*/}
+list=false
+nosf=false
+lnopt="s"
+lnsuf=""
+stderrdir=""
 
-        for ex in ${ignore[@]}; do
-            [[ ${file#*$PWD/} == $ex ]] && ig=true && break || ig=false 
-        done
-        [[ $ig == true ]] && continue
+while getopts "hlnfo" opt; do
+    case $opt in
+        h)
+            echo "$USAGE"
+            exit
+            ;;
+        l)
+            list=true
+            ;;
+        n)
+            nosf=true
+            ;;
+        f)    
+            lnopt="sf" 
+            ;;
+        o)
+            stderrdir=/dev/null
+            ;;
+        \?)
+            echo "$USAGE"
+            exit
+            ;;
+    esac
+done
 
-        file=${file##*/}
-        if [[ $dir == "" ]]; then
-            path=$HOME/$file
-        else
-            dir=$dir/
-            path=$HOME/$dir$file
-        fi
 
-        echo "Creating Symlink to $dir$file at $path"
-        [[ $1 == "-f" ]] && ln -sf "$PWD/$dir$file" "$path" || ln -s "$PWD/$dir$file" "$path"
-        
-        # just to be safe
-        if [[ $? > "0"  ]] && [[ ! $1 == "-f" ]] && [[ ! $1 == "-n" ]]; then
-            read -p "Use force? [Y/N]: " uforce
-            case $uforce in
-                [Yy]* ) ln -sf "$PWD/$dir$file" "$path" && echo Done;;
-                [Nn]* | * ) echo "Skipping.." && continue;;
-            esac
-        fi
+cd ~/dotfiles/
+files=$(find $PWD -type f)
+
+for file in $files; do
+    dir=${file%/*}
+    dir=${dir#*$PWD}
+    dir=${dir#*/}
+
+    for ex in ${ignore[@]}; do
+        [[ ${file#*$PWD/} == $ex ]] && ig=true && break || ig=false 
     done
-fi
+
+    [[ $ig == true ]] && continue
+
+    [[ $list == true ]] && echo "$file" && continue
+
+    file=${file##*/}
+    if [[ $dir == "" ]]; then
+        path=$HOME/$file
+    else
+        dir=$dir/
+        path=$HOME/$dir$file
+    fi
+
+    # create folders in case they don't exist
+    mkdir --parents $HOME/$dir
+
+    echo "Creating Symlink to $dir$file at $path"
+
+    if [[ $stderrdir == "" ]]; then
+        ln -$lnopt "$PWD/$dir$file" "$path"
+    else
+        ln -$lnopt "$PWD/$dir$file" "$path" 2>$stderrdir
+    fi
+
+    # just to be safe
+    if [[ $? > "0"  ]] && [[ ! $lnopt == "sf" ]] && [[ ! $nosf == "true" ]]; then
+        echo "Failed!"
+        read -p "Use force? [Y/N]: " uforce
+        case $uforce in
+            [Yy]* ) ln -sf "$PWD/$dir$file" "$path" && echo Done;;
+            [Nn]* | * ) echo "Skipping.." && continue;;
+        esac
+    fi
+done
